"""
Security Report Generator
Aggregates results from the password, phishing, and file scan modules
into a single composite report. Any combination of the three inputs is
optional — the report reflects only what was actually analyzed.
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional


def generate_report(
    password_result: Optional[Dict] = None,
    phishing_result: Optional[Dict] = None,
    file_result: Optional[Dict] = None,
) -> Dict:
    """
    Build a composite security report from up to three scan results.

    Args:
        password_result: Output of check_password_strength(), or None.
        phishing_result: Output of detect_phishing(), or None.
        file_result: Output of scan_file(), or None.

    Returns:
        Dict with overall_security_score, component breakdown,
        recommendations, next_steps, and a timestamp.
    """
    components: List[Dict] = []
    recommendations: List[str] = []
    scores: List[float] = []

    if password_result:
        pct = password_result.get("percentage", 0)
        scores.append(pct)
        components.append({
            "name": "Password Strength",
            "status": password_result.get("strength", "Unknown"),
            "score_percent": pct,
        })
        if pct < 60:
            recommendations.append("Strengthen the analyzed password or replace it with a passphrase generated by a password manager.")
        if password_result.get("details", {}).get("is_common") or password_result.get("details", {}).get("is_common_variant"):
            recommendations.append("Immediately change any account using a common or breached password.")

    if phishing_result and "risk_score" in phishing_result:
        risk = phishing_result.get("risk_score", 0)
        pct = max(0, 100 - (risk * 10))
        scores.append(pct)
        components.append({
            "name": "URL Safety",
            "status": phishing_result.get("risk_level", "Unknown"),
            "score_percent": pct,
        })
        if risk > 2:
            recommendations.append("Avoid clicking the analyzed URL and verify the sender through an official channel.")

    if file_result and "risk_score" in file_result:
        risk = file_result.get("risk_score", 0)
        pct = max(0, 100 - (risk * 100 / 12))
        scores.append(pct)
        components.append({
            "name": "File Safety",
            "status": file_result.get("threat_level", "Unknown"),
            "score_percent": round(pct, 1),
        })
        if risk > 3:
            recommendations.append("Do not open the analyzed file without scanning it with antivirus software first.")

    if scores:
        overall_score = round(sum(scores) / len(scores), 1)
    else:
        overall_score = None

    if not recommendations:
        if components:
            recommendations.append("No urgent issues found in the analyzed items. Keep following standard security practices.")
        else:
            recommendations.append("Run a password, URL, or file check to generate a personalized report.")

    recommendations.append("Enable two-factor authentication on your important accounts if you haven't already.")
    recommendations.append("Keep software and operating systems up to date.")

    next_steps = [
        "Review any flagged items above before taking action",
        "Re-run checks periodically, especially for passwords and links you're unsure about",
        "Consider a password manager and a reputable antivirus solution for ongoing protection",
    ]

    return {
        "overall_security_score": overall_score,
        "components_analyzed": len(components),
        "components": components,
        "recommendations": recommendations,
        "next_steps": next_steps,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "note": "This report reflects only the items you analyzed in this session. It is educational and not a substitute for a professional security assessment.",
      }
  
